import assert from "node:assert/strict";
import test from "node:test";
import { nativeUiFixture } from "./native-ui-fixture.js";

test("project and conversation schedules, edit, pause, history, delete and Cron filter", { timeout: 180_000 }, async (t) => {
  const { page, environment, node } = await nativeUiFixture(t);
  await page.goto(node.url);
  await page.locator('#loginDialog[open]').waitFor();
  await page.locator("#loginUsernameInput").fill(environment.username);
  await page.locator("#loginPasswordInput").fill(environment.password);
  await page.locator("#loginSubmitButton").click();
  await page.waitForFunction(() => document.querySelectorAll("#projectList .list-row").length === 3);
  await page.locator('[aria-label="Actions for Internal Assistant"]').click();
  await page.locator('[data-testid="project-cron-button"]').click();
  await page.waitForFunction(() => document.querySelector("#cronDialog").open && document.querySelector("#cronForm").elements.ownerNodeId.options.length > 0);
  await page.locator("#cronNew").click();
  assert.equal(await page.evaluate(`(() => {
    const form = document.querySelector("#cronForm"), f = form.elements;
    f.name.value = "Project browser cron"; f.prompt.value = "Scheduled project prompt";
    f.frequency.value = "weekly"; f.frequency.dispatchEvent(new Event("change", { bubbles: true }));
    f.timezone.value = "UTC"; f.enabled.checked = false;
    if (document.querySelector("#cronWeekdayLabel").hidden || document.querySelector("#cronTimeLabel").hidden || !document.querySelector("#cronMinuteLabel").hidden) throw Error("Weekly controls incorrect");
    if (document.querySelector("#cronEngineLabel").hidden) throw Error("Project task needs an agent selector");
    form.requestSubmit(); return true;
  })()`), true);
  await page.waitForFunction(() => document.querySelector("#cronList").textContent.includes("Project browser cron · New conversationPaused"));
  await page.locator('[data-testid="cron-edit"]').click();
  assert.equal(await page.evaluate(`(() => {
    const form = document.querySelector("#cronForm"), f = form.elements;
    if (f.frequency.value !== "weekly" || f.timezone.value !== "UTC" || f.enabled.checked) throw Error("Saved schedule not restored");
    f.name.value = "Edited project cron"; f.frequency.value = "daily";
    f.frequency.dispatchEvent(new Event("change", { bubbles: true }));
    if (!document.querySelector("#cronWeekdayLabel").hidden) throw Error("Daily schedule shows weekday");
    form.requestSubmit(); return true;
  })()`), true);
  await page.waitForFunction(() => document.querySelector("#cronList").textContent.includes("Edited project cron"));
  await page.locator('[data-testid="cron-toggle"]').click();
  await page.waitForFunction(() => document.querySelector("#cronList").textContent.includes("Next:"));
  await page.locator('[data-testid="cron-toggle"]').click();
  await page.waitForFunction(() => document.querySelector("#cronList").textContent.includes("Paused"));
  await page.locator('[data-testid="cron-history"]').click();
  await page.waitForFunction(() => document.querySelector("#cronList pre")?.textContent === "Not run yet");
  await page.locator("#cronClose").click();
  await page.locator("#projectList .list-row", { hasText: "Internal Assistant" }).locator("button").first().click();
  await page.locator('[data-filter="all"]').click();
  await page.waitForFunction(() => [...document.querySelectorAll("#sessionList .list-row")].some(row => row.textContent.includes("Short one")));
  await page.locator("#sessionList .list-row", { hasText: "Short one" }).locator(".row-menu-button").click();
  await page.locator('[data-testid="session-cron-button"]').click();
  await page.waitForFunction(() => document.querySelector("#cronDialog").open && document.querySelector("#cronList").textContent.includes("No scheduled tasks"));
  await page.locator("#cronNew").click();
  assert.equal(await page.evaluate(`(() => {
    const form = document.querySelector("#cronForm"), f = form.elements;
    if (!document.querySelector("#cronEngineLabel").hidden) throw Error("Conversation should inherit its agent");
    f.name.value = "Conversation browser cron"; f.prompt.value = "Scheduled append";
    f.timezone.value = "UTC"; f.enabled.checked = false;
    form.requestSubmit(); return true;
  })()`), true);
  await page.waitForFunction(() => document.querySelector("#cronList").textContent.includes("Conversation browser cron · Existing conversationPaused"));
  await page.locator("#cronClose").click();
  await page.locator('[data-testid="chats-filter-cron-button"]').click();
  await page.waitForFunction(() => document.querySelectorAll("#sessionList .list-row").length === 1 && document.querySelector("#sessionList .list-row").textContent.includes("Short one"));
  await page.goto(node.url);
  await page.waitForFunction(() => document.querySelector("[data-filter-count=cron]").textContent === "1");
  await page.locator('[aria-label="Actions for Internal Assistant"]').click();
  await page.locator('[data-testid="project-cron-button"]').click();
  await page.waitForFunction(() => document.querySelectorAll("#cronList .cron-task").length === 2);
  await page.locator("#cronList .cron-task", { hasText: "Edited project cron" }).getByTestId("cron-delete").click();
  await page.locator('#confirmDialog[open]').waitFor();
  await page.locator("#confirmAcceptButton").click();
  await page.waitForFunction(() => document.querySelectorAll("#cronList .cron-task").length === 1);
  assert.equal(await page.evaluate('document.querySelector("#cronList").textContent.includes("Conversation browser cron") && !document.querySelector("#cronList").textContent.includes("Edited project cron")'), true);
});
