import assert from "node:assert/strict";
import test from "node:test";
import { nativeUiFixture } from "./native-ui-fixture.js";
import { api, signIn } from "../dev-nodes.js";

test("mobile search plus and C/N gestures open project-selectable creation without hijacking scrolling", { timeout: 180_000 }, async t => {
  const fixture = await nativeUiFixture(t);
  await api(fixture.node, await signIn(fixture.environment, fixture.node), "PUT", "/preferences", { focusUiEnabled: true });
  const context = await fixture.page.context().browser()!.newContext({ viewport: { width: 390, height: 650 }, hasTouch: true, isMobile: true, serviceWorkers: "block" });
  t.after(() => context.close());
  const page = await context.newPage();
  page.setDefaultTimeout(10_000);
  await page.goto(fixture.node.url);
  await page.getByTestId("login-username-input").fill(fixture.environment.username);
  await page.getByTestId("login-password-input").fill(fixture.environment.password);
  await page.getByTestId("login-submit-button").click();
  await page.locator(".project-card", { hasText: "Internal Assistant" }).first().click();
  await page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))));
  const search = await page.getByTestId("conversation-list-search-input").boundingBox();
  const plus = await page.getByTestId("conversation-search-create-button").boundingBox();
  assert.ok(search && plus && Math.abs(search.y + search.height / 2 - plus.y - plus.height / 2) < 2 && plus.x >= search.x + search.width, `plus sits beside search: ${JSON.stringify({ search, plus })}`);
  await page.getByTestId("conversation-search-create-button").tap();
  await page.getByTestId("new-session-name-dialog").waitFor();
  assert.equal(await page.getByTestId("new-session-project-select").inputValue(), "Internal Assistant");
  await page.getByTestId("new-session-project-select").fill("Joint Bob");
  await page.getByTestId("new-session-project-option").getByText("Joint Bob", { exact: true }).click();
  await page.getByTestId("new-session-name-cancel-button").click();
  await page.getByTestId("new-session-name-dialog").waitFor({ state: "hidden" });
  const cdp = await context.newCDPSession(page);
  const draw = async (points: Array<{ x: number; y: number }>) => {
    await cdp.send("Input.dispatchTouchEvent", { type: "touchStart", touchPoints: [points[0]] });
    for (const point of points.slice(1)) await cdp.send("Input.dispatchTouchEvent", { type: "touchMove", touchPoints: [point] });
    await cdp.send("Input.dispatchTouchEvent", { type: "touchEnd", touchPoints: [] });
  };
  assert.ok(await page.locator("#sessionList").evaluate(el => el.scrollHeight > el.clientHeight), "fixture must overflow to test scrolling");
  const scrollBefore = await page.locator("#sessionList").evaluate(el => el.scrollTop);
  await draw(Array.from({ length: 25 }, (_, i) => ({ x: 180, y: 600 - i * 10 })));
  await page.waitForFunction(before => document.querySelector("#sessionList")!.scrollTop > before, scrollBefore);
  assert.equal(await page.getByTestId("new-session-name-dialog").isVisible(), false, "ordinary scrolling does not create a conversation");
  await draw(Array.from({ length: 41 }, (_, i) => ({ x: 190 + 80 * Math.cos(i * Math.PI / 20), y: 440 + 80 * Math.sin(i * Math.PI / 20) })));
  assert.equal(await page.getByTestId("new-session-name-dialog").isVisible(), false, "the replaced O gesture no longer opens creation");
  await draw(Array.from({ length: 41 }, (_, i) => ({ x: 190 + 80 * Math.cos(-Math.PI / 3 - i * Math.PI / 30), y: 440 + 80 * Math.sin(-Math.PI / 3 - i * Math.PI / 30) })));
  await page.getByTestId("new-session-name-dialog").waitFor();
  assert.equal(await page.getByTestId("new-session-project-select").inputValue(), "Internal Assistant", "C defaults to the active project, not a cancelled selection");
  await page.getByTestId("new-session-name-cancel-button").click();
  const corners = [{ x: 120, y: 550 }, { x: 120, y: 350 }, { x: 270, y: 550 }, { x: 270, y: 350 }];
  await draw(corners.slice(1).flatMap((end, segment) => Array.from({ length: 16 }, (_, i) => ({ x: corners[segment].x + (end.x - corners[segment].x) * i / 15, y: corners[segment].y + (end.y - corners[segment].y) * i / 15 }))));
  await page.getByTestId("quick-note-dialog").waitFor();
  await page.waitForFunction(() => !document.querySelector<HTMLButtonElement>("[data-testid='quick-note-save-button']")!.disabled);
  assert.equal(await page.getByTestId("quick-note-project-select").inputValue(), "Internal Assistant");
  await page.getByTestId("quick-note-project-select").fill("Joint Bob");
  await page.getByTestId("quick-note-project-options").getByRole("option", { name: "Joint Bob", exact: true }).click();
  await page.getByTestId("quick-note-cancel-button").tap();
  await page.getByTestId("quick-note-dialog").waitFor({ state: "hidden" });
  const referenceN = [[250, 1420], [280, 1335], [315, 1215], [340, 1080], [365, 990], [400, 935], [400, 1050], [405, 1150], [425, 1270], [455, 1355], [490, 1400], [520, 1395], [550, 1340], [575, 1245], [610, 1120], [650, 1000], [685, 925], [725, 880], [770, 850]];
  await draw(referenceN.map(([x, y]) => ({ x: 100 + (x - 250) * 0.3, y: 320 + (y - 850) * 0.35 })));
  await page.getByTestId("quick-note-dialog").waitFor();
  assert.equal(await page.getByTestId("quick-note-project-select").inputValue(), "Internal Assistant", "the curved N opens Add note for the active project");
  await page.getByTestId("quick-note-cancel-button").tap();
  await page.getByTestId("quick-note-dialog").waitFor({ state: "hidden" });
  await page.setViewportSize({ width: 1280, height: 900 });
  assert.equal(await page.getByTestId("conversation-search-create-button").isVisible(), false, "desktop unchanged");
});
