import assert from "node:assert/strict";
import test from "node:test";
import { nativeUiFixture } from "./native-ui-fixture.js";
import { api, signIn } from "../dev-nodes.js";

test("double taps suppress controls, triple taps only open pinnable recents, single taps still work", { timeout: 180_000 }, async t => {
  const fixture = await nativeUiFixture(t);
  const session = await signIn(fixture.environment, fixture.node);
  await api(fixture.node, session, "PUT", "/preferences", { focusUiEnabled: true });
  const context = await fixture.page.context().browser()!.newContext({ viewport: { width: 390, height: 844 }, hasTouch: true, isMobile: true, serviceWorkers: "block" });
  const page = await context.newPage();
  page.setDefaultTimeout(20_000);
  await page.goto(fixture.node.url);
  await page.getByTestId("login-username-input").fill(fixture.environment.username);
  await page.getByTestId("login-password-input").fill(fixture.environment.password);
  await page.getByTestId("login-submit-button").click();
  await page.locator("body.focus-ui .project-card").first().waitFor();
  await page.locator(".project-card", { hasText: "Internal Assistant" }).first().click();
  await page.locator("#sessionList .session-card").first().click();
  await page.waitForFunction(() => !document.querySelector<HTMLTextAreaElement>("#messageInput")!.disabled);
  await page.locator("#messageInput").fill("Gesture-safe draft");
  const fab = page.getByTestId("focus-controls-button");
  await fab.tap();
  await page.locator("#focusControls").waitFor();
  const note = await page.getByTestId("focus-new-note").boundingBox();
  assert.ok(note);
  await page.touchscreen.tap(note.x + 20, note.y + 20);
  await page.touchscreen.tap(note.x + 20, note.y + 20);
  await page.waitForFunction(() => document.querySelector<HTMLElement>("#focusControlsButton")!.hidden);
  assert.equal(await page.getByTestId("quick-note-dialog").isVisible(), false, "double tap must not create a note first");
  const title = await page.locator("#sessionTitle").boundingBox();
  assert.ok(title);
  for (let i = 0; i < 3; i++) await page.touchscreen.tap(title.x + 10, title.y + 10);
  await page.getByTestId("recent-sessions-dialog").waitFor();
  assert.equal(await fab.isVisible(), false, "triple tap must not restore the hidden FAB");
  const pin = page.getByTestId("recent-session-pin-button").first();
  const savedPin = page.waitForResponse(response => response.url().endsWith("/api/pins") && response.request().method() === "PUT");
  await pin.tap();
  assert.equal((await savedPin).ok(), true);
  await page.waitForFunction(() => document.querySelector("#recentSessionsList .pin-button")!.getAttribute("aria-label")!.startsWith("Unpin"));
  const stored = await api<{ conversations: unknown[] }>(fixture.node, session, "GET", "/pins");
  assert.equal(stored.body.conversations.length, 1, "pin persists for quick navigation");
  await page.getByTestId("recent-session-option").first().tap();
  await page.getByTestId("recent-sessions-dialog").waitFor({ state: "hidden" });
  await page.waitForFunction(() => document.querySelector<HTMLTextAreaElement>("#messageInput")!.value === "Gesture-safe draft");
  await page.keyboard.press("Control+.");
  await page.locator("#focusControls").waitFor();
  const control = await page.getByTestId("focus-new-note").boundingBox();
  assert.ok(control);
  for (let i = 0; i < 3; i++) await page.touchscreen.tap(control.x + 20, control.y + 20);
  await page.getByTestId("recent-sessions-dialog").waitFor();
  assert.equal(await fab.isVisible(), true, "triple tap must not hide the visible FAB");
  assert.equal(await page.getByTestId("quick-note-dialog").isVisible(), false, "triple tap suppresses the control too");
  await context.close();
});
