import assert from "node:assert/strict";
import { mkdtemp, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { type Browser } from "playwright-core";
import { launchChrome } from "./launch-chrome.js";
import { seedDevEnvironment, startDevNode, stopDevNode } from "../dev-nodes.js";

test("searchable secret-type picker filters accounts and starts new accounts on the chosen provider", { timeout: 240_000 }, async () => {
  const root = await mkdtemp(path.join(os.tmpdir(), "joint-bob-stripe-secrets-"));
  const environment = await seedDevEnvironment(root, 1);
  const node = environment.nodes[0];
  const server = await startDevNode(environment, node);
  let browser: Browser | undefined;
  try {
    browser = await launchChrome({ headless: true });
    const page = await browser.newPage({ viewport: { width: 1440, height: 900 }, serviceWorkers: "block" });
    const errors: string[] = [];
    page.on("pageerror", (error) => errors.push(error.message));
    await page.goto(node.url);
    await page.getByTestId("login-username-input").fill(environment.username);
    await page.getByTestId("login-password-input").fill(environment.password);
    await page.getByTestId("login-submit-button").click();
    await page.getByText("Internal Assistant", { exact: true }).waitFor();
    await page.getByTestId("settings-open-button").click();
    await page.getByTestId("settings-tab-secrets").click();
    const picker = page.getByTestId("secret-type-select");
    assert.equal(await page.locator("#secretTypeTabs").count(), 0, "old tab row is gone");
    assert.equal(await picker.getAttribute("data-value"), "all");
    await picker.click();
    const search = page.getByTestId("secret-type-select-search");
    await search.fill("stri");
    const options = page.getByTestId("secret-type-select-option");
    assert.deepEqual(await options.allTextContents(), ["Stripe"]);
    assert.ok((await options.first().locator("svg path").getAttribute("d"))?.startsWith("M19.9 4.4"), "Stripe option uses brand icon");
    await options.first().click();
    assert.equal(await picker.getAttribute("data-value"), "stripe");
    assert.ok((await picker.locator("svg path").getAttribute("d"))?.startsWith("M19.9 4.4"), "chosen provider has an icon");
    await page.getByTestId("secret-account-list").getByText("No Stripe accounts.").waitFor();
    await page.getByTestId("secret-account-add-button").click();
    assert.equal(await page.getByTestId("secret-account-provider-input").getAttribute("data-value"), "stripe");
    assert.equal(await page.getByTestId("secret-variable-name-input").inputValue(), "STRIPE_API_KEY");
    assert.equal(await page.getByTestId("secret-variable-kind-select").inputValue(), "value");
    const iconPath = await page.getByTestId("secret-account-provider-icon").locator("svg path").getAttribute("d");
    assert.ok(iconPath?.startsWith("M19.9 4.4"), "Stripe form uses its own icon");
    await page.getByTestId("secret-account-label-input").fill("Stripe test");
    await page.getByTestId("secret-variable-value-input").fill("sk_test_synthetic");
    const created = page.waitForResponse((response) => response.url().endsWith("/api/secrets/accounts") && response.request().method() === "POST");
    await page.getByTestId("secret-account-save-button").click();
    const response = await created;
    assert.equal(response.status(), 201);
    const body = await response.json() as { account: { provider: string; variables: Array<{ name: string; value?: string }> } };
    assert.equal(body.account.provider, "stripe");
    assert.deepEqual(body.account.variables, [{ name: "STRIPE_API_KEY", kind: "value", configured: true }]);
    await page.getByTestId("secret-account-dialog").waitFor({ state: "hidden" });
    const row = page.getByTestId("secret-account-list").locator('.secret-account-row[data-provider="stripe"]');
    await row.getByText("Stripe test · Stripe").waitFor();
    assert.ok((await row.getByTestId("secret-account-provider-badge").locator("svg path").getAttribute("d"))?.startsWith("M19.9 4.4"));
    await row.getByTestId("secret-account-edit-button").click();
    assert.equal(await page.getByTestId("secret-variable-value-input").inputValue(), "");
    assert.equal(await page.getByTestId("secret-variable-name-input").inputValue(), "STRIPE_API_KEY");
    const card = page.locator("#secretAccountForm");
    const dialogBody = page.getByTestId("secret-account-dialog-body");
    const heightBefore = (await card.boundingBox())!.height;
    for (let index = 0; index < 8; index += 1) await page.getByTestId("secret-variable-add-button").click();
    const heightAfter = (await card.boundingBox())!.height;
    assert.equal(heightAfter, heightBefore, "adding variables does not resize the dialog");
    assert.ok(heightAfter <= 900, "dialog fits the viewport");
    const scroll = await dialogBody.evaluate((element) => ({ overflow: element.scrollHeight > element.clientHeight, cardScrolls: element.parentElement!.scrollHeight > element.parentElement!.clientHeight }));
    assert.ok(scroll.overflow, "the dialog body scrolls once the rows overflow");
    assert.equal(scroll.cardScrolls, false, "only the body scrolls; heading and actions stay put");
    assert.ok(await page.getByTestId("secret-account-save-button").isVisible());
    await page.getByTestId("secret-account-cancel-button").click();

    await picker.click();
    await search.fill("cloud");
    assert.deepEqual(await options.allTextContents(), ["Cloudflare"]);
    assert.ok((await options.first().locator("svg path").getAttribute("d"))?.startsWith("M20.2 13.2"));
    await options.first().click();
    await page.getByTestId("secret-account-list").getByText("No Cloudflare accounts.").waitFor();
    await page.getByTestId("secret-account-add-button").click();
    assert.equal(await page.getByTestId("secret-account-provider-input").getAttribute("data-value"), "cloudflare");
    assert.equal(await page.getByTestId("secret-variable-name-input").inputValue(), "CLOUDFLARE_API_KEY");
    assert.ok((await page.getByTestId("secret-account-provider-icon").locator("svg path").getAttribute("d"))?.startsWith("M20.2 13.2"));
    await page.getByTestId("secret-account-label-input").fill("Cloudflare test");
    await page.getByTestId("secret-variable-value-input").fill("synthetic-cf-key");
    const cloudflareCreated = page.waitForResponse((response) => response.url().endsWith("/api/secrets/accounts") && response.request().method() === "POST");
    await page.getByTestId("secret-account-save-button").click();
    const cloudflareResponse = await cloudflareCreated;
    assert.equal(cloudflareResponse.status(), 201);
    const cloudflareBody = await cloudflareResponse.json() as { account: { provider: string; variables: Array<{ name: string; value?: string }> } };
    assert.equal(cloudflareBody.account.provider, "cloudflare");
    assert.deepEqual(cloudflareBody.account.variables, [{ name: "CLOUDFLARE_API_KEY", kind: "value", configured: true }]);
    await page.getByTestId("secret-account-dialog").waitFor({ state: "hidden" });
    const cloudflareRow = page.getByTestId("secret-account-list").locator('.secret-account-row[data-provider="cloudflare"]');
    await cloudflareRow.getByText("Cloudflare test · Cloudflare").waitFor();
    assert.ok((await cloudflareRow.getByTestId("secret-account-provider-badge").locator("svg path").getAttribute("d"))?.startsWith("M20.2 13.2"));
    await picker.click();
    await search.fill("missing provider");
    assert.equal(await page.getByTestId("secret-type-select-options").innerText(), "No types found");
    await search.fill("all");
    await options.first().click();
    assert.equal(await picker.getAttribute("data-value"), "all");
    await cloudflareRow.waitFor();
    for (const [query, label] of [["openai", "OpenAI"], ["z.ai", "Z.AI"], ["graphana", "Grafana"], ["data dog", "Datadog"], ["postgre", "PostgreSQL"], ["ms sql", "MS SQL"], ["mognodb", "MongoDB"]]) {
      await picker.click();
      await search.fill(query);
      assert.deepEqual(await options.allTextContents(), [label]);
      assert.equal(await options.first().locator("svg path").count() > 0, true, `${label} has an icon`);
      await search.press("Escape");
    }
    await page.getByTestId("secret-account-add-button").click();
    const provider = page.getByTestId("secret-account-provider-input");
    const providerSearch = page.getByTestId("secret-account-provider-input-search");
    assert.equal(await providerSearch.evaluate((input) => input === document.activeElement), true, "plus opens the searchable type picker");
    await providerSearch.fill("mognodb");
    assert.deepEqual(await page.getByTestId("secret-account-provider-input-option").allTextContents(), ["MongoDB"]);
    await providerSearch.press("Enter");
    assert.equal(await provider.getAttribute("data-value"), "mongodb");
    assert.equal(await page.getByTestId("secret-variable-name-input").inputValue(), "MONGODB_URI");
    await page.getByTestId("secret-account-label-input").fill("Test MongoDB");
    await page.getByTestId("secret-variable-value-input").fill("mongodb://synthetic.invalid/test");
    const mongoCreated = page.waitForResponse((response) => response.url().endsWith("/api/secrets/accounts") && response.request().method() === "POST");
    await page.getByTestId("secret-account-save-button").click();
    assert.equal((await mongoCreated).status(), 201);
    await page.getByTestId("secret-account-dialog").waitFor({ state: "hidden" });
    await picker.click(); await search.fill("mongo"); await options.first().click();
    await page.getByTestId("secret-account-list").getByText("Test MongoDB · MongoDB").waitFor();
    assert.deepEqual(errors, []);
  } finally {
    await browser?.close();
    await stopDevNode(server);
    await rm(root, { recursive: true, force: true });
  }
});
