import assert from "node:assert/strict";
import { mkdtemp, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { type Browser } from "playwright-core";
import { launchChrome } from "./launch-chrome.js";
import { seedDevEnvironment, startDevNode, stopDevNode } from "../dev-nodes.js";

test("searchable secret-type picker filters accounts and starts new accounts on the chosen provider", { timeout: 240_000 }, async () => {
  const root = await mkdtemp(path.join(os.tmpdir(), "joint-bob-stripe-secrets-"));
  const environment = await seedDevEnvironment(root, 1);
  const node = environment.nodes[0];
  const server = await startDevNode(environment, node);
  let browser: Browser | undefined;
  try {
    browser = await launchChrome({ headless: true });
    const page = await browser.newPage({ viewport: { width: 1440, height: 900 }, serviceWorkers: "block" });
    const errors: string[] = [];
    page.on("pageerror", (error) => errors.push(error.message));
    await page.goto(node.url);
    await page.getByTestId("login-username-input").fill(environment.username);
    await page.getByTestId("login-password-input").fill(environment.password);
    await page.getByTestId("login-submit-button").click();
    await page.getByText("Internal Assistant", { exact: true }).waitFor();
    await page.getByTestId("settings-open-button").click();
    await page.getByTestId("settings-tab-secrets").click();
    const picker = page.getByTestId("secret-type-select");
    assert.equal(await page.locator("#secretTypeTabs").count(), 0, "old tab row is gone");
    assert.equal(await picker.getAttribute("data-value"), "all");
    await picker.click();
    const search = page.getByTestId("secret-type-select-search");
    await search.fill("stri");
    const options = page.getByTestId("secret-type-select-option");
    assert.deepEqual(await options.allTextContents(), ["Stripe"]);
    assert.ok((await options.first().locator("svg path").getAttribute("d"))?.startsWith("M19.9 4.4"), "Stripe option uses brand icon");
    await options.first().click();
    assert.equal(await picker.getAttribute("data-value"), "stripe");
    assert.ok((await picker.locator("svg path").getAttribute("d"))?.startsWith("M19.9 4.4"), "chosen provider has an icon");
    await page.getByTestId("secret-account-list").getByText("No Stripe accounts.").waitFor();
    await page.getByTestId("secret-account-add-button").click();
    assert.equal(await page.getByTestId("secret-account-provider-input").inputValue(), "stripe");
    assert.equal(await page.getByTestId("secret-variable-name-input").inputValue(), "STRIPE_API_KEY");
    assert.equal(await page.getByTestId("secret-variable-kind-select").inputValue(), "value");
    const iconPath = await page.getByTestId("secret-account-provider-icon").locator("svg path").getAttribute("d");
    assert.ok(iconPath?.startsWith("M19.9 4.4"), "Stripe form uses its own icon");
    await page.getByTestId("secret-account-label-input").fill("Stripe test");
    await page.getByTestId("secret-variable-value-input").fill("sk_test_synthetic");
    const created = page.waitForResponse((response) => response.url().endsWith("/api/secrets/accounts") && response.request().method() === "POST");
    await page.getByTestId("secret-account-save-button").click();
    const response = await created;
    assert.equal(response.status(), 201);
    const body = await response.json() as { account: { provider: string; variables: Array<{ name: string; value?: string }> } };
    assert.equal(body.account.provider, "stripe");
    assert.deepEqual(body.account.variables, [{ name: "STRIPE_API_KEY", kind: "value", configured: true }]);
    await page.getByTestId("secret-account-dialog").waitFor({ state: "hidden" });
    const row = page.getByTestId("secret-account-list").locator('.secret-account-row[data-provider="stripe"]');
    await row.getByText("Stripe test · Stripe").waitFor();
    assert.ok((await row.getByTestId("secret-account-provider-badge").locator("svg path").getAttribute("d"))?.startsWith("M19.9 4.4"));
    await row.getByTestId("secret-account-edit-button").click();
    assert.equal(await page.getByTestId("secret-variable-value-input").inputValue(), "");
    assert.equal(await page.getByTestId("secret-variable-name-input").inputValue(), "STRIPE_API_KEY");
    await page.getByTestId("secret-account-cancel-button").click();

    await picker.click();
    await search.fill("cloud");
    assert.deepEqual(await options.allTextContents(), ["Cloudflare"]);
    assert.ok((await options.first().locator("svg path").getAttribute("d"))?.startsWith("M20.2 13.2"));
    await options.first().click();
    await page.getByTestId("secret-account-list").getByText("No Cloudflare accounts.").waitFor();
    await page.getByTestId("secret-account-add-button").click();
    assert.equal(await page.getByTestId("secret-account-provider-input").inputValue(), "cloudflare");
    assert.equal(await page.getByTestId("secret-variable-name-input").inputValue(), "CLOUDFLARE_API_KEY");
    assert.ok((await page.getByTestId("secret-account-provider-icon").locator("svg path").getAttribute("d"))?.startsWith("M20.2 13.2"));
    await page.getByTestId("secret-account-label-input").fill("Cloudflare test");
    await page.getByTestId("secret-variable-value-input").fill("synthetic-cf-key");
    const cloudflareCreated = page.waitForResponse((response) => response.url().endsWith("/api/secrets/accounts") && response.request().method() === "POST");
    await page.getByTestId("secret-account-save-button").click();
    const cloudflareResponse = await cloudflareCreated;
    assert.equal(cloudflareResponse.status(), 201);
    const cloudflareBody = await cloudflareResponse.json() as { account: { provider: string; variables: Array<{ name: string; value?: string }> } };
    assert.equal(cloudflareBody.account.provider, "cloudflare");
    assert.deepEqual(cloudflareBody.account.variables, [{ name: "CLOUDFLARE_API_KEY", kind: "value", configured: true }]);
    await page.getByTestId("secret-account-dialog").waitFor({ state: "hidden" });
    const cloudflareRow = page.getByTestId("secret-account-list").locator('.secret-account-row[data-provider="cloudflare"]');
    await cloudflareRow.getByText("Cloudflare test · Cloudflare").waitFor();
    assert.ok((await cloudflareRow.getByTestId("secret-account-provider-badge").locator("svg path").getAttribute("d"))?.startsWith("M20.2 13.2"));
    await picker.click();
    await search.fill("missing provider");
    assert.equal(await page.getByTestId("secret-type-select-options").innerText(), "No types found");
    await search.fill("all");
    await options.first().click();
    assert.equal(await picker.getAttribute("data-value"), "all");
    await cloudflareRow.waitFor();
    assert.deepEqual(errors, []);
  } finally {
    await browser?.close();
    await stopDevNode(server);
    await rm(root, { recursive: true, force: true });
  }
});
